controller_list:
  - name: fake_manpluator_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: manpluator
    pose: home